### ISSUE TITLE
gglot2 graph plot issue.

### ISSUE THREAD

**Issue by EngineerDanny** [EngineerDanny/Rperform#4]
After, running the ` Rperform::plot_branchmetrics(test_path = "tests/testthat/test-CRAN.R", metric = "time", branch1 = "l1loss", branch2 = "master", save_data = T, save_plots = F)` function on the [binsegRcpp](https://github.com/tdhock/binsegRcpp) repository, comparing the **master** and **l1loss** branch. I recorded a time_frame of 254 observations and 8 variables.
Below is how the graph looks like :

![Rplot](https://user-images.githubusercontent.com/47421661/175354036-fac662dd-328b-448b-9ee0-bbeec77a03b4.png)

You could see that information is not depicted clearly on the graph.
My hypothesis is that it was caused as a result of the larger data set.
Potential fix will be breaking down the data sets and plotting their respective graphs.

**Comment by tdhock** [comment]
thanks for sharing. not sure what the problem with that plot is.
1. can you share the files which were generated?
2. why are there only two commits on the X axis? there should be several dozen in that branch.

**Comment by EngineerDanny** [comment]
This was the data set generated when the function was ran.
👉 [time_frame.csv](https://github.com/EngineerDanny/Rperform/files/8975441/time_frame.csv)

Yes, there are actually several commits on that branch. But the **plot_branchmetrics** function works differently as explained [here](https://github.com/analyticalmonk/Rperform/wiki/Plotting-package-metrics-with-Rperform#commits-across-two-branches).

**Master** : It only tests **the latest commit** in this branch .In this case, it is [Merge pull request...](https://github.com/tdhock/binsegRcpp/commit/71de83db39d14c75d6d85f9d2e133a951d0b0122) commit.

**PR Branch** : It tests all the commits in this branch after the **latest common commit** among the two branches. In this case, it is [checks ok](https://github.com/tdhock/binsegRcpp/commit/5a150dfbf4f8934e802b6cead6add3c09c111ace) commit.

This explains why there are only two commits on the X-axis.

**Comment by EngineerDanny** [comment]
This is how the commit history looks for the **master** and **l1loss** branches respectively.

<img width="1228" alt="Screenshot 2022-06-24 at 11 09 37 AM" src="https://user-images.githubusercontent.com/47421661/175523626-d64690ba-9c90-4f11-98d7-00a5137dfd6a.png">

<img width="1228" alt="Screenshot 2022-06-24 at 11 09 17 AM" src="https://user-images.githubusercontent.com/47421661/175523616-248817bb-c466-4726-8c85-c62c3e3c5a03.png">

**Comment by tdhock** [comment]
there were 42 commits in the corresponding PR, which was already merged with master. https://github.com/tdhock/binsegRcpp/pull/10/commits
maybe you need to refer to the explicit commit SHA1 IDs to get a time series of 42 commits?

**Comment by EngineerDanny** [comment]
Yh. It looks like it squashed the 42 commits into just one merge request commit and used that.

**Comment by EngineerDanny** [comment]
@tdhock I have been looking into this, when the test_names are many. This means there are lots of testthat blocks in just one file. Hence a longer graph output.

![ggsave1](https://user-images.githubusercontent.com/47421661/182020124-e00c8acb-ebfd-4478-9019-ace4c98fc3ac.png)

**Comment by EngineerDanny** [comment]
@tdhock The new update exposes vital parameters like the `height_in_inches` and `width_in_inches`. 
Do you think I should expose `res` too ?

**Comment by tdhock** [comment]
yes that could be useful
